CRITICAL - 2025-04-25 02:36:49 --> ErrorException: Cannot use App\Models\UserModel as UserModel because the name is already in use
[Method: GET, Route: /]
in ROOTPATH\tests\UserModelTest.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-04-25 14:23:52 --> Exception: Unable to prepare statement: 1, no such table: db_user in C:\Users\user\Desktop\DevOps_Project\system\Database\SQLite3\Connection.php:176
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\SQLite3\Connection.php(176): SQLite3->query('SELECT *\nFROM `...')
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testDindAllUsers()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#17 {main}
ERROR - 2025-04-25 14:23:54 --> Exception: no such table: db_user in C:\Users\user\Desktop\DevOps_Project\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\SQLite3\Connection.php(175): SQLite3->exec('INSERT INTO `db...')
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('INSERT INTO `db...')
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#18 {main}
ERROR - 2025-04-25 14:36:24 --> mysqli_sql_exception: Table 'devops_tp.tests_user' doesn't exist in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#17 {main}
ERROR - 2025-04-25 14:36:24 --> mysqli_sql_exception: Table 'devops_tp.tests_user' doesn't exist in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `te...', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `te...')
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `te...')
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `te...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#18 {main}
